import mongoose from 'mongoose';
import { connectDatabase, disconnectDatabase } from '../config/db.js';
import User from '../models/User.js'; import Test from '../models/Test.js'; import Lab from '../models/Lab.js'; import Booking from '../models/Booking.js'; import Report from '../models/Report.js';
import { hashPassword } from '../utils/password.js';

const password = 'Mango@123';
const tests = [
  ['CBC', 'CBC', 'Complete blood count with key blood health markers.', 500, 'No special preparation', 'Blood', 6], ['Lipid Profile', 'Heart', 'Cholesterol and triglycerides panel.', 799, '8-10 hours fasting', 'Blood', 8], ['HbA1c', 'Diabetes', 'Three-month blood sugar average.', 450, 'No fasting required', 'Blood', 6], ['Thyroid Profile', 'Thyroid', 'T3, T4 and TSH thyroid screening.', 699, 'No special preparation', 'Blood', 8], ['Liver Function Test', 'Liver', 'Markers for liver health.', 899, '8 hours fasting recommended', 'Blood', 12], ['Kidney Function Test', 'Kidney', 'Kidney health and filtration markers.', 850, 'Drink water normally', 'Blood', 12], ['Vitamin D', 'Vitamins', 'Vitamin D deficiency screening.', 799, 'No special preparation', 'Blood', 24], ['Vitamin B12', 'Vitamins', 'B12 level screening.', 650, 'No special preparation', 'Blood', 24], ['Iron Profile', 'Full Body', 'Iron, TIBC and transferrin saturation.', 899, '8 hours fasting recommended', 'Blood', 18], ['Full Body Checkup', 'Preventive Health', 'A thoughtful preventive health panel.', 1999, '8-10 hours fasting', 'Blood and urine', 24]
].map(([name, category, description, price, preparation, sampleType, turnaroundHours]) => ({ name, category, description, price, preparation, sampleType, turnaroundHours, active: true, parameters: [{ name: name === 'CBC' ? 'Hemoglobin' : 'Primary marker', unit: name === 'CBC' ? 'g/dL' : 'mg/dL', refMin: 12, refMax: 17, normalRange: '12-17' }] }));
const labs = [{ name: 'Mango HealthLab Andheri', city: 'Mumbai', address: '18 Link Road, Andheri West', phone: '+91 22 4400 1200', email: 'andheri@mangohealthlab.local', operatingHours: { open: '08:00', close: '20:00' }, homeCollectionAvailable: true }, { name: 'Mango HealthLab Indiranagar', city: 'Bengaluru', address: '42 12th Main, Indiranagar', phone: '+91 80 4400 1200', email: 'indiranagar@mangohealthlab.local', operatingHours: { open: '08:00', close: '20:00' }, homeCollectionAvailable: true }, { name: 'Mango HealthLab Baner', city: 'Pune', address: '6 High Street, Baner', phone: '+91 20 4400 1200', email: 'baner@mangohealthlab.local', operatingHours: { open: '08:00', close: '20:00' }, homeCollectionAvailable: false }];
await connectDatabase(); await Promise.all([User.deleteMany({}), Test.deleteMany({}), Lab.deleteMany({}), Booking.deleteMany({}), Report.deleteMany({})]);
const users = await User.create(await Promise.all([{ name: 'Rahul Sharma', email: 'patient@mangohealthlab.test', phone: '9876543210', role: 'PATIENT' }, { name: 'Meera Kapoor', email: 'admin@mangohealthlab.test', phone: '9876543211', role: 'ADMIN' }, { name: 'Arjun Rao', email: 'staff@mangohealthlab.test', phone: '9876543212', role: 'PHLEBOTOMIST' }, { name: 'Dr. Anika Shah', email: 'doctor@mangohealthlab.test', phone: '9876543213', role: 'DOCTOR' }].map(async user => ({ ...user, passwordHash: await hashPassword(password) }))));
await Test.create(tests); await Lab.create(labs); console.log('Seed complete. Demo password:', password); await disconnectDatabase();
